[profile.default]
src = "contracts"
test = "test/foundry"
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[invariant]
runs = 256
depth = 512
fail_on_revert = false
