#!/usr/bin/env node
// Regenerate src/abis.ts from Hardhat compilation artifacts.
// Run from repo root: node --loader ts-node/esm packages/protocol/scripts/gen-abis.ts
// Or via: npm run gen-abis (from packages/protocol/)
import { Interface } from "ethers";
import * as fs from "fs";
import * as path from "path";

const REPO_ROOT = path.resolve(__dirname, "../../..");
const OUT = path.resolve(__dirname, "../src/abis.ts");

function load(artifactPath: string): object[] {
  const json = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, artifactPath), "utf8"));
  return json.abi;
}

function format(abi: object[]): string[] {
  return Interface.from(abi).format();
}

const registryAbi = format(load("artifacts/contracts/QuoteRegistry.sol/QuoteRegistry.json"));
const escrowAbi   = format(load("artifacts/contracts/SLAEscrow.sol/SLAEscrow.json"));
const timelockAbi = format(load("artifacts/@openzeppelin/contracts/governance/TimelockController.sol/TimelockController.json"));

const lines = [
  `// AUTO-GENERATED by packages/protocol/scripts/gen-abis.ts -- do not edit by hand.`,
  `// Re-run: npm run gen-abis (from packages/protocol/) after any contract change.`,
  ``,
  `export const REGISTRY_ABI = [`,
  ...registryAbi.map((s) => `  ${JSON.stringify(s)},`),
  `] as const;`,
  ``,
  `export const ESCROW_ABI = [`,
  ...escrowAbi.map((s) => `  ${JSON.stringify(s)},`),
  `] as const;`,
  ``,
  `export const TIMELOCK_ABI = [`,
  ...timelockAbi.map((s) => `  ${JSON.stringify(s)},`),
  `] as const;`,
  ``,
];

fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT}`);
console.log(`  REGISTRY_ABI: ${registryAbi.length} entries`);
console.log(`  ESCROW_ABI:   ${escrowAbi.length} entries`);
console.log(`  TIMELOCK_ABI: ${timelockAbi.length} entries`);
