#!/usr/bin/env node
// Regenerate src/addresses.ts from deployments/<chainId>.json files.
// Run from repo root: node --loader ts-node/esm packages/protocol/scripts/gen-addresses.ts
// Or via: npm run gen-addresses (from packages/protocol/)
import * as fs   from "fs";
import * as path from "path";

const REPO_ROOT   = path.resolve(__dirname, "../../..");
const DEPLOY_DIR  = path.join(REPO_ROOT, "deployments");
const OUT         = path.resolve(__dirname, "../src/addresses.ts");

interface RawDeployment {
  chainId: string;
  network: string;
  registry: string;
  escrow: string;
  escrowImpl: string;
  timelock: string;
  feeRecipient: string;
  deployedAtBlock?: number;
}

const files = fs.readdirSync(DEPLOY_DIR)
  .filter(f => /^\d+\.json$/.test(f))
  .sort((a, b) => parseInt(a) - parseInt(b));

const deployments: Array<{ chainId: number; raw: RawDeployment }> = [];
for (const file of files) {
  const raw: RawDeployment = JSON.parse(fs.readFileSync(path.join(DEPLOY_DIR, file), "utf8"));
  const chainId = parseInt(raw.chainId);
  if (chainId === 31337) continue; // skip localhost
  deployments.push({ chainId, raw });
}

function entry(raw: RawDeployment): string[] {
  const lines = [
    `    registry:        ${JSON.stringify(raw.registry)},`,
    `    escrow:          ${JSON.stringify(raw.escrow)},`,
    `    escrowImpl:      ${JSON.stringify(raw.escrowImpl)},`,
    `    timelock:        ${JSON.stringify(raw.timelock)},`,
    `    feeRecipient:    ${JSON.stringify(raw.feeRecipient)},`,
  ];
  if (raw.deployedAtBlock !== undefined)
    lines.push(`    deployedAtBlock: ${raw.deployedAtBlock},`);
  return lines;
}

const body = deployments.map(({ chainId, raw }) => [
  `  /** ${raw.network} (${raw.chainId}) */`,
  `  ${chainId}: {`,
  ...entry(raw),
  `  },`,
].join("\n")).join("\n");

const out = [
  `// AUTO-GENERATED by packages/protocol/scripts/gen-addresses.ts -- do not edit by hand.`,
  `// Re-run: npm run gen-addresses (from packages/protocol/) after any deployment.`,
  ``,
  `export interface Deployment {`,
  `  registry: string;`,
  `  escrow: string;`,
  `  escrowImpl: string;`,
  `  timelock: string;`,
  `  feeRecipient: string;`,
  `  deployedAtBlock?: number;`,
  `}`,
  ``,
  `/** Known deployments keyed by chainId. Mainnet (8453) not yet deployed. */`,
  `export const DEPLOYMENTS: Record<number, Deployment> = {`,
  body,
  `};`,
  ``,
].join("\n");

fs.writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
for (const { chainId, raw } of deployments)
  console.log(`  ${chainId} (${raw.network}): block ${raw.deployedAtBlock ?? "unknown"}`);
