#!/usr/bin/env node
// Regenerate src/abis.ts from Hardhat compilation artifacts.
// Run from repo root: node --loader ts-node/esm packages/protocol/scripts/gen-abis.ts
// Or via: npm run gen-abis (from packages/protocol/)
import { Interface } from "ethers";
import * as fs from "fs";
import * as path from "path";

const REPO_ROOT = path.resolve(__dirname, "../../..");
const OUT = path.resolve(__dirname, "../src/abis.ts");

function load(contract: string): object[] {
  const artifact = path.join(
    REPO_ROOT,
    "artifacts/contracts",
    `${contract}.sol`,
    `${contract}.json`
  );
  const json = JSON.parse(fs.readFileSync(artifact, "utf8"));
  return json.abi;
}

function format(abi: object[]): string[] {
  return Interface.from(abi).format();
}

const registryAbi = format(load("QuoteRegistry"));
const escrowAbi = format(load("SLAEscrow"));

const lines = [
  `// AUTO-GENERATED by packages/protocol/scripts/gen-abis.ts -- do not edit by hand.`,
  `// Re-run: npm run gen-abis (from packages/protocol/) after any contract change.`,
  ``,
  `export const REGISTRY_ABI = [`,
  ...registryAbi.map((s) => `  ${JSON.stringify(s)},`),
  `] as const;`,
  ``,
  `export const ESCROW_ABI = [`,
  ...escrowAbi.map((s) => `  ${JSON.stringify(s)},`),
  `] as const;`,
  ``,
];

fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT}`);
console.log(`  REGISTRY_ABI: ${registryAbi.length} entries`);
console.log(`  ESCROW_ABI:   ${escrowAbi.length} entries`);
