export const TIMELOCK_ABI = [
  "function PROPOSER_ROLE() view returns (bytes32)",
  "function EXECUTOR_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function hasRole(bytes32, address) view returns (bool)",
  "function grantRole(bytes32, address)",
  "function revokeRole(bytes32, address)",
  "function renounceRole(bytes32, address)",
  "function hashOperation(address, uint256, bytes, bytes32, bytes32) view returns (bytes32)",
  "function isOperationPending(bytes32) view returns (bool)",
  "function isOperationReady(bytes32) view returns (bool)",
  "function isOperationDone(bytes32) view returns (bool)",
  "function getTimestamp(bytes32) view returns (uint256)",
  "function getMinDelay() view returns (uint256)",
  "function schedule(address, uint256, bytes, bytes32, bytes32, uint256)",
  "function execute(address, uint256, bytes, bytes32, bytes32)",
] as const;
