name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Forge
    env:
      FOUNDRY_INVARIANT_RUNS: 32
      FOUNDRY_INVARIANT_DEPTH: 64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Check formatting
        run: make fmt

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage

      - name: Slither
        uses: crytic/slither-action@v0.4.2
        with:
          slither-args: --compile-force-framework foundry --filter-paths 'lib/'
          fail-on: low

      - name: Aderyn Check
        uses: Cyfrin/aderyn-ci@v0
        with:
          fail-on: low
