name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Forge

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        run: |
          set -eux
          curl -L https://foundry.paradigm.xyz | bash
          "$HOME/.foundry/bin/foundryup"
          echo "$HOME/.foundry/bin" >> "$GITHUB_PATH"

      - name: Check formatting
        run: forge fmt --check

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test

      - name: Coverage
        run: forge coverage
